[project]
name = "util-math"
version = "0.1.0"
description = "Shared math utilities"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["util_math"]
