services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: services/web/Dockerfile
    environment:
      FASTAPI_BASE_URL: http://api:8000
    ports:
      - "8001:8001"
    depends_on:
      - api
    restart: unless-stopped
