[tool.ruff]
line-length = 100
target-version = "py311"
extend-include = ["packages", "services"]
lint.select = ["E", "F", "I", "UP", "B"]
format.preview = true

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-q --maxfail=1"
testpaths = ["packages", "services"]

[tool.coverage.run]
branch = true
source = ["packages", "services"]

[tool.coverage.report]
show_missing = true
skip_covered = true
