[project]
name = "data-io"
version = "0.1.0"
description = "Data IO helpers"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "util-math @ file://{root}/../util_math",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["data_io"]
